Repository 25web/climatechange, pull requests merged in 2022-11, with the labels that each got.

#23 add v1 data to db
  docs/webdb.sql
Labels: database

#22 1 loginf
  frontend/package-lock.json
  frontend/package.json
  frontend/public/manifest.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/axios.js
  frontend/src/components/Login.js
  frontend/src/components/Register.js
  frontend/src/css/LR.scss
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/setupTests.js
Labels: frontend

#29 Add nodemon
  backend/package-lock.json
  backend/package.json
Labels: enhancement

#30 Fix axios BaseURL
  frontend/src/axios.js
Labels: bug, backend

#27 Database chart values
  docs/webdb.sql
Labels: database

#45 add v6
  backend/controllers/chartController.js
  backend/models/chartModel.js
  backend/routes/chartRoutes.js
  frontend/src/App.js
  frontend/src/components/charts/V6.js
Labels: frontend
